#:schema https://mise.jdx.dev/schema/mise.json

[env]
JAX_DEFAULT_MATMUL_PRECISION = "highest"
JAX_ENABLE_X64 = "true"
XLA_PYTHON_CLIENT_PREALLOCATE = "false"

[task_config]
includes = [".config/copier/mise-tasks", ".config/mise/tasks"]
